---
dist: trusty
sudo: false

language: python
python:
  - 3.6

cache:
  pip: true
  directories:
    - eggs/

before_install:
  - pip install -r requirements.txt

install:
  - buildout

script:
  - bin/test

notifications:
  email:
    on_success: never
    on_failure: never
